server:
  port: 8000
spring:
  application:
    name: gateway
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
    
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${WEB_SITE_URL:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      routes:
        - id: user-public-routes
          uri: ${USER_ROUTE_URI:http://localhost:8001}
          predicates:
              - Path=/v1/users            # TEMPORAL

        - id: magazines-public-routes
        - uri: ${MAGAZINE_ROUTE_URI:http://localhost:8002}
        - predicates:
              - Path=/v1/magazines