jwt:
  secret: ${JWT_SECRET}
  time: ${JWT_TIME}
  zone: ${ZONE}
server:
  port: 8000
spring:
  application:
    name: gateway
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
    
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${VM_IP:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            maxAge: 3600
      routes:
        - id: user-public-routes
          uri: ${USER_ROUTE_URI:http://localhost:8001}
          predicates:
            - Path=/v1/users/login,/v1/users/register,/v1/magazines/getAll
        - id: user-private-routes
          uri: ${USER_ROUTE_URI:http://localhost:8001}
          predicates:
            - Path=/v1/users/**,/v1/magazines/**,/v1/suscriptions/**,/v1/categories/**
          # TODO: ADD PUBLIC ADD ROUTES TO SHOW ROUTES IN ANY COMPONENT IN THE FRONTEND
        - id: ads-public-routes
          uri: ${ADS_ROUTE_URI:http://localhost:8003}
          predicates:
            - Path=/v1/ads/random/**,/v1/ads/views/{id}
        - id: ads-private-routes
          uri: ${ADS_ROUTE_URI:http://localhost:8003}
          predicates:
            - Path=/v1/ads/**,/v1/temp-categories/**,/v1/periods/**
          filters:
            - VerifyJWTFilterFactory
