CREATE TABLE IF NOT EXISTS labels (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE  IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_has_information (
    id INT AUTO_INCREMENT PRIMARY KEY,
    FK_User INT NOT NULL REFERENCES users(id),
    photo_path VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    description VARCHAR(255) NOT NULL,
    current_balance DECIMAL(10,2) DEFAULT 0.00
) ENGINE=InnoDB;