CREATE TABLE IF NOT EXISTS pages (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    FK_Module INT NOT NULL REFERENCES modules(id),
    path VARCHAR(50) NOT NULL,
    is_enabled TINYINT(1) DEFAULT 1
);

CREATE TABLE IF NOT EXISTS roles_has_pages (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FK_Role INT NOT NULL REFERENCES roles(id),
    FK_Page INT NOT NULL REFERENCES pages(id)
);