CREATE TABLE IF NOT EXISTS periods (
    id INT AUTO_INCREMENT PRIMARY KEY,
    period_add ENUM ('DAY', 'THREEDAYS', 'ONEWEEK', 'TWOWEEKS') NOT NULL,
    cost DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS adds_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name ENUM ('TEXT', 'IMAGE', 'VIDEO') NOT NULL
);
